#!/usr/bin/env bash -i


echo "Compiling haml"
haml index.haml > index.html

echo "Committing changes to git"
git add .
git commit . -m "update"

echo "Pushing to remote origin"
git push origin gh-pages
