#!/usr/bin/env ruby

require 'rubygems'
require 'fssm'

dir=File.dirname(__FILE__)

FSSM.monitor(dir, '**/*') do
  update {|base, relative|
    puts "#{Time.now.to_s} updated #{base} - #{relative}"
    `bash update` if relative =~ /haml$/
  }
  delete {|base, relative|
    puts "deleted"
  }
  create {|base, relative|
    puts "created"
  }
end

